### ISSUE TITLE
login aunthentication failed

### ISSUE THREAD

**Issue by nakumiayumu144** [ponlponl123/-Prototype-AIVTuber#12]
Is there something wrong?
![image](https://user-images.githubusercontent.com/127565115/225442646-0887693b-74a8-4ffb-857d-14f117d3406c.png)
![image](https://user-images.githubusercontent.com/127565115/225442143-fed2e430-f96e-4b8b-b7da-895fc2867198.png)

**Comment by ponlponl123** [comment]
I see that the `twitch_token` variable is similar to the Client Secret if I'm not mistaken, what twitch needs to verify its identity is a **Token**, not a **Client Secret key**.

Try following this video (from TheM3ss)
[https://youtu.be/qgQcwIKSEeY](https://youtu.be/qgQcwIKSEeY?t=138)
If everything is correct You'll get the same results as `138s` or `2:18` seconds of the video.

**Comment by nakumiayumu144** [comment]
error: Login unsuccessful
![image](https://user-images.githubusercontent.com/127565115/225458061-2a8470f1-8d2f-4cd2-9b81-d58649a001a9.png)

**Comment by Lwnlcks** [comment]
The token is formatted as "oauth:~".

You can also use [this site](https://twitchapps.com/tmi/) to create tokens.

**Comment by Lwnlcks** [comment]
"twitch_channel" does not enter url.
In this case, type "#naakumi".

**Comment by nakumiayumu144** [comment]
> The token is formatted as "oauth:~".
> 
> You can also use [this site](https://twitchapps.com/tmi/) to create tokens.

thank you for helping, it's working now
