### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nakumiayumu144** [ponlponl123/-Prototype-AIVTuber#14]
1. how do I enable Subtitles?
2. How can I change the voice and language we want?
3. Can we add some backstory to the Ai?

**Comment by ponlponl123** [comment]
1. You can go to localhost:8000/tts to see the subtitle when running Node.
2. You can go to https://docs.aws.amazon.com/polly/latest/dg/voicelist.html to find a model for the language you want
3. You can tell the AI to add more about his story. Before asking your questions like:
```
await openai.createCompletion({
         model: 'davinci',
         prompt: `Hey CHARACTER_NAME! You are now CHARACTER_NAME who can answer anything. and is an expert. everyone will start talking Talk to you with the prefix Q:, but you don't need to prefix with the A:.\n
Q: YOUR_QUESTION
\nA:`,
         temperature: 0.9,
         max_tokens: 100,
         stop: ["ChatGPT:", "Adrian Twarog:", '\n'],
       });
```

**Comment by nakumiayumu144** [comment]
>     3. You can tell the AI to add more about his story. Before asking your questions like:
> 
> 
> ```
> await openai.createCompletion({
>          model: 'davinci',
>          prompt: `Hey CHARACTER_NAME! You are now CHARACTER_NAME who can answer anything. and is an expert. everyone will start talking Talk to you with the prefix Q:, but you don't need to prefix with the A:.\n
> Q: YOUR_QUESTION
> \nA:`,
>          temperature: 0.9,
>          max_tokens: 100,
>          stop: ["ChatGPT:", "Adrian Twarog:", '\n'],
>        });
> ```

sorry but I don't know where to put it, can you tell me how to do it, because I don't have any coding basics at all :(

**Comment by nakumiayumu144** [comment]
How can Ai read the names of people in chat?

**Comment by ponlponl123** [comment]
sure! You can use `${tags.username}` to get the user's name!

**Comment by nakumiayumu144** [comment]
> 
> ```
> await openai.createCompletion({
>          model: 'davinci',
>          prompt: `Hey CHARACTER_NAME! You are now CHARACTER_NAME who can answer anything. and is an expert. everyone will start talking Talk to you with the prefix Q:, but you don't need to prefix with the A:.\n
> Q: YOUR_QUESTION
> \nA:`,
>          temperature: 0.9,
>          max_tokens: 100,
>          stop: ["ChatGPT:", "Adrian Twarog:", '\n'],
>        });
> ```
I'm using this code but I feel like the Ai is talking to itself.
i don't understand using model davinci
![image](https://user-images.githubusercontent.com/127565115/225643955-d1e83d3f-475b-4a45-bf9c-87bbcd639f2d.png)
Something like that A: or Q:
![image](https://user-images.githubusercontent.com/127565115/225648318-980117be-fa73-4174-a873-ea152e1fccc3.png)

**Comment by nakumiayumu144** [comment]
can i see you parameters for Vtube Studio because i don't how to use [VTS Desktop Audio Plugin](https://lualucky.itch.io/vts-desktop-audio-plugin)?

**Comment by NovaPlayzGames** [comment]
Hey, firstly i would like to say using the normal davinci models are not recommended for chatting applications, this is basiclly what this project is, that being said i have made some adjustments on my repo to better reflect these changes and recommendations from open ai, [https://github.com/InsanityLabs/AIVTuber](https://github.com/InsanityLabs/AIVTuber)
