### ISSUE TITLE
Is there code without the AWS?

### ISSUE THREAD

**Issue by rawnullbyte** [ponlponl123/-Prototype-AIVTuber#2]

**Comment by ponlponl123** [comment]
Text-to-Speech (TTS) technology converts written text into spoken words. While AWS services such as Amazon Polly provide TTS functionality, it is also possible to implement TTS without AWS in Node.js. Here are a few libraries that you can use for TTS in Node.js:

- eSpeak: This is a compact open-source software speech synthesizer for English and other languages. You can use the eSpeak module in Node.js to generate speech from text.
- 
- Google Cloud Text-to-Speech API: Google provides a cloud-based TTS API that you can use to generate spoken words from text. You can access this API using the google-cloud library in Node.js.
- 
- MaryTTS: MaryTTS is an open-source, multilingual Text-to-Speech Synthesis platform written in Java. You can use the MaryTTS API in Node.js to generate speech from text.

Here is a code example that demonstrates how you can use Google Cloud Text-to-Speech API in Node.js:
```
const fs = require("fs");
const request = require("request");

// Replace with your Google Cloud API key
const API_KEY = "YOUR_API_KEY";

// The text to convert to speech
const text = "Hello, I am a computer program created with OpenAI";

// The request options for the API
const options = {
  url: "https://texttospeech.googleapis.com/v1beta1/text:synthesize",
  method: "POST",
  headers: {
    "Authorization": "Bearer " + API_KEY,
    "Content-Type": "application/json"
  },
  json: {
    "input": {
      "text": text
    },
    "voice": {
      "languageCode": "en-US",
      "name": "en-US-Wavenet-C"
    },
    "audioConfig": {
      "audioEncoding": "MP3"
    }
  }
};

// Make the API request
request(options, function (error, response, body) {
  if (!error && response.statusCode === 200) {
    // Write the audio data to a file
    fs.writeFile("output.mp3", body.audioContent, "base64", function (err) {
      if (err) {
        console.error(err);
      } else {
        console.log("The file was saved!");
      }
    });
  } else {
    console.error(error);
  }
});
```
